### ISSUE TITLE
Sign command fails with syntax error

### ISSUE THREAD

**Issue by cmrd-senya** [bin3xish477/cloudfront-signed-cookies#4]
Sign command fails for me with syntax error:
```
senya@senya-Latitude-5511:/tmp$ python3.8 -m cloudfront_signed_cookies sign -p /home/senya/.../private_key.pem -k ... -r '...path'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/senya/.local/lib/python3.8/site-packages/cloudfront_signed_cookies/__main__.py", line 4, in <module>
    from cloudfront_signed_cookies.cli import main
  File "/home/senya/.local/lib/python3.8/site-packages/cloudfront_signed_cookies/cli/__init__.py", line 4, in <module>
    from cloudfront_signed_cookies.cli.genkeys import genkeys
  File "/home/senya/.local/lib/python3.8/site-packages/cloudfront_signed_cookies/cli/genkeys/__init__.py", line 13
    open("private_key.pem", mode="wb") as priv_key_file,
                                       ^
SyntaxError: invalid syntax

```

**Comment by bin3xish477** [comment]
Released a new [version](https://pypi.org/project/cloudfront-signed-cookies/1.2/) (v1.2) and it's working as expected:

Ran the following command successfully:
```
python3 -m cloudfront_signed_cookies sign -p private_key.pem -k 'AFJD902SA' -r 'http://someresource.com/private.txt'
```

Example Output:

```
curl --silent --header 'Cookie: CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cDovL3NvbWVyZXNvdXJjZS5jb20vcHJpdmF0ZS50eHQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2ODk5MjMxODl9fX1dfQ__; Secure; HttpOnly' --header 'Cookie: CloudFront-Signature=g5Fv6pqcIg2s2ij2BRm5pT9wvvjmPrpmO6fpCTyDwLy4Wpd~hXA~vhcul-jkvEYdquJv~20JiNc-gPUvsWFcNVuWiIYwsgfFv2fUzNLyF4zPaZZ~gto8B0tQdeGHzTfFwZnB7NwhNYb8QQ25ROEuKbgOGJV6q1j76dC02jItKJh3-9K~AjaqIp7N-ZrNA4uNZXsKu~y9Pe~XYUJY1l9-ADG2PnIucmTqrPQ4ZLR5sQ2S-Cv6ZITh45wdvT5F8KmQVtuGKWaW7JIm8ArKtff7SbrFDa4X7RtldB9GQqJix5S7VnNlEhnBOX9I0-qknRMmeJmmabAN6i83MnWTKDfIVA__; Secure; HttpOnly' --header 'Cookie: CloudFront-Key-Pair-Id=AFJD902SA; Secure; HttpOnly' --url 'http://someresource.com/private.txt'
```
